version: '3.4'
services:
  db:
    image: mongo:3.6-jessie
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
  bot:
    build: .
    command: nodemon -L --inspect=0.0.0.0:5858
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/tacoguy
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://db/taco_guy